export const themePresetOptions = [
  "dark-minimal",
  "gothic-black",
  "soft-neutral",
  "luxury-serif",
  "neon-accent",
  "mono-studio",
  "earth-tone",
  "high-contrast",
  "copper-glow",
  "studio-paper",
] as const;

export const backgroundTypeOptions = ["solid", "gradient", "image"] as const;
export const radiusStyleOptions = ["small", "medium", "large"] as const;
export const themeModeOptions = ["dark", "light"] as const;
export const fontPairingPresetOptions = [
  "bold-modern",
  "elegant-editorial",
  "minimal-sans",
  "edgy-clean",
  "premium-editorial",
] as const;

export const headingFontOptions = [
  { value: "display-serif", label: "Display Serif" },
  { value: "modern-sans", label: "Modern Sans" },
  { value: "gothic-sans", label: "Gothic Sans" },
  { value: "editorial-serif", label: "Editorial Serif" },
  { value: "mono-display", label: "Mono Display" },
] as const;

export const bodyFontOptions = [
  { value: "clean-sans", label: "Clean Sans" },
  { value: "neutral-sans", label: "Neutral Sans" },
  { value: "editorial-sans", label: "Editorial Sans" },
  { value: "mono-body", label: "Mono Body" },
] as const;

export const themePresets = {
  "dark-minimal": {
    label: "Dark Minimal",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#09090b",
    gradientStart: "#111114",
    gradientEnd: "#09090b",
    primaryColor: "#f7b15d",
    secondaryColor: "#2b2c31",
    cardColor: "#131316",
    cardOpacity: 0.78,
    headingFont: "display-serif",
    bodyFont: "clean-sans",
    fontPairingPreset: "premium-editorial",
    radiusStyle: "large",
  },
  "gothic-black": {
    label: "Gothic Black",
    themeMode: "dark",
    backgroundType: "gradient",
    backgroundColor: "#050505",
    gradientStart: "#000000",
    gradientEnd: "#1b1b1d",
    primaryColor: "#d7d1c8",
    secondaryColor: "#232325",
    cardColor: "#0d0d10",
    cardOpacity: 0.84,
    headingFont: "gothic-sans",
    bodyFont: "neutral-sans",
    fontPairingPreset: "edgy-clean",
    radiusStyle: "medium",
  },
  "soft-neutral": {
    label: "Soft Neutral",
    themeMode: "light",
    backgroundType: "gradient",
    backgroundColor: "#f4efe7",
    gradientStart: "#f5efe8",
    gradientEnd: "#ddd6c8",
    primaryColor: "#3b3129",
    secondaryColor: "#e6ddd2",
    cardColor: "#fffaf4",
    cardOpacity: 0.88,
    headingFont: "editorial-serif",
    bodyFont: "editorial-sans",
    fontPairingPreset: "elegant-editorial",
    radiusStyle: "large",
  },
  "luxury-serif": {
    label: "Luxury Serif",
    themeMode: "dark",
    backgroundType: "gradient",
    backgroundColor: "#120d11",
    gradientStart: "#241521",
    gradientEnd: "#0b090c",
    primaryColor: "#d7b48a",
    secondaryColor: "#3d2a34",
    cardColor: "#1a1218",
    cardOpacity: 0.8,
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
    fontPairingPreset: "elegant-editorial",
    radiusStyle: "large",
  },
  "neon-accent": {
    label: "Neon Accent",
    themeMode: "dark",
    backgroundType: "gradient",
    backgroundColor: "#071117",
    gradientStart: "#0d2030",
    gradientEnd: "#071117",
    primaryColor: "#4ee5d2",
    secondaryColor: "#132933",
    cardColor: "#0d161c",
    cardOpacity: 0.76,
    headingFont: "modern-sans",
    bodyFont: "clean-sans",
    fontPairingPreset: "bold-modern",
    radiusStyle: "medium",
  },
  "mono-studio": {
    label: "Mono Studio",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#0b0b0d",
    gradientStart: "#151519",
    gradientEnd: "#09090b",
    primaryColor: "#f3f3f3",
    secondaryColor: "#202126",
    cardColor: "#121317",
    cardOpacity: 0.82,
    headingFont: "mono-display",
    bodyFont: "mono-body",
    fontPairingPreset: "minimal-sans",
    radiusStyle: "small",
  },
  "earth-tone": {
    label: "Earth Tone",
    themeMode: "dark",
    backgroundType: "gradient",
    backgroundColor: "#17120d",
    gradientStart: "#2b2018",
    gradientEnd: "#140f0b",
    primaryColor: "#d5965b",
    secondaryColor: "#2a241e",
    cardColor: "#1c1713",
    cardOpacity: 0.8,
    headingFont: "display-serif",
    bodyFont: "neutral-sans",
    fontPairingPreset: "premium-editorial",
    radiusStyle: "large",
  },
  "high-contrast": {
    label: "High Contrast",
    themeMode: "light",
    backgroundType: "solid",
    backgroundColor: "#ffffff",
    gradientStart: "#ffffff",
    gradientEnd: "#ececec",
    primaryColor: "#111111",
    secondaryColor: "#ebebeb",
    cardColor: "#ffffff",
    cardOpacity: 0.96,
    headingFont: "modern-sans",
    bodyFont: "clean-sans",
    fontPairingPreset: "bold-modern",
    radiusStyle: "medium",
  },
  "copper-glow": {
    label: "Copper Glow",
    themeMode: "dark",
    backgroundType: "gradient",
    backgroundColor: "#120e0c",
    gradientStart: "#2b1d17",
    gradientEnd: "#0f0b09",
    primaryColor: "#c98a52",
    secondaryColor: "#37251c",
    cardColor: "#171210",
    cardOpacity: 0.84,
    headingFont: "display-serif",
    bodyFont: "neutral-sans",
    fontPairingPreset: "premium-editorial",
    radiusStyle: "large",
  },
  "studio-paper": {
    label: "Studio Paper",
    themeMode: "light",
    backgroundType: "gradient",
    backgroundColor: "#f4ede2",
    gradientStart: "#f8f3eb",
    gradientEnd: "#ddd1c0",
    primaryColor: "#2e2923",
    secondaryColor: "#e5dbcf",
    cardColor: "#fffaf2",
    cardOpacity: 0.94,
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
    fontPairingPreset: "elegant-editorial",
    radiusStyle: "medium",
  },
} as const;

export type ThemePresetKey = (typeof themePresetOptions)[number];
export type BackgroundType = (typeof backgroundTypeOptions)[number];
export type RadiusStyle = (typeof radiusStyleOptions)[number];
export type ThemeMode = (typeof themeModeOptions)[number];
export type FontPairingPreset = (typeof fontPairingPresetOptions)[number];
export type HeadingFontKey = (typeof headingFontOptions)[number]["value"];
export type BodyFontKey = (typeof bodyFontOptions)[number]["value"];
