export const themePresetOptions = [
  "bronze-studio",
  "smoke-metal",
  "dark-alloy",
  "velvet-sable",
  "cathedral-ash",
  "astral-forge",
] as const;

export const backgroundTypeOptions = ["solid", "gradient", "image"] as const;
export const radiusStyleOptions = ["small", "medium", "large"] as const;
export const themeModeOptions = ["dark", "light"] as const;
export const fontPairingPresetOptions = [
  "inter-neutral",
  "manrope-refined",
  "outfit-modern",
] as const;

export const headingFontOptions = [
  { value: "inter", label: "Inter" },
  { value: "manrope", label: "Manrope" },
  { value: "outfit", label: "Outfit" },
] as const;

export const bodyFontOptions = [
  { value: "inter", label: "Inter" },
  { value: "manrope", label: "Manrope" },
  { value: "outfit", label: "Outfit" },
] as const;

export const themePresets = {
  "bronze-studio": {
    label: "Bronz Gece",
    description: "Sıcak bronz tonlar ve koyu zemin.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#121212",
    background: "#121212",
    gradientStart: "#121212",
    gradientEnd: "#121212",
    textColor: "#F5F1EA",
    text: "#F5F1EA",
    mutedText: "#B8AEA3",
    primaryColor: "#C89B5D",
    primary: "#C89B5D",
    secondaryColor: "#8E6B43",
    secondary: "#8E6B43",
    buttonText: "#181411",
    cardColor: "#1A1A1C",
    surface: "#1A1A1C",
    cardOpacity: 0.94,
    border: "#2C241D",
    overlay: "rgba(12, 10, 8, 0.52)",
    headingFont: "inter",
    bodyFont: "inter",
    fontPairingPreset: "inter-neutral",
    radiusStyle: "medium",
  },
  "smoke-metal": {
    label: "Koyu Mermer",
    description: "Daha nötr, daha sakin, daha premium.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#141518",
    background: "#141518",
    gradientStart: "#141518",
    gradientEnd: "#141518",
    textColor: "#F3F2EE",
    text: "#F3F2EE",
    mutedText: "#AEAEA8",
    primaryColor: "#D6C6A5",
    primary: "#D6C6A5",
    secondaryColor: "#8A7F73",
    secondary: "#8A7F73",
    buttonText: "#171717",
    cardColor: "#1C1E22",
    surface: "#1C1E22",
    cardOpacity: 0.94,
    border: "#2A2D33",
    overlay: "rgba(10, 11, 13, 0.50)",
    headingFont: "manrope",
    bodyFont: "manrope",
    fontPairingPreset: "manrope-refined",
    radiusStyle: "medium",
  },
  "dark-alloy": {
    label: "Gece Moru",
    description: "Mor vurgulu güçlü ve modern görünüm.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#100F16",
    background: "#100F16",
    gradientStart: "#100F16",
    gradientEnd: "#100F16",
    textColor: "#F5F3FF",
    text: "#F5F3FF",
    mutedText: "#B9B2D9",
    primaryColor: "#8B5CF6",
    primary: "#8B5CF6",
    secondaryColor: "#C084FC",
    secondary: "#C084FC",
    buttonText: "#F8F5FF",
    cardColor: "#181622",
    surface: "#181622",
    cardOpacity: 0.94,
    border: "#2A243B",
    overlay: "rgba(11, 8, 18, 0.54)",
    headingFont: "outfit",
    bodyFont: "inter",
    fontPairingPreset: "outfit-modern",
    radiusStyle: "medium",
  },
  "velvet-sable": {
    label: "Kül Siyahı",
    description: "En sade ve en sert koyu tema.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#111111",
    background: "#111111",
    gradientStart: "#111111",
    gradientEnd: "#111111",
    textColor: "#FAFAF9",
    text: "#FAFAF9",
    mutedText: "#B5B1AC",
    primaryColor: "#E7E5E4",
    primary: "#E7E5E4",
    secondaryColor: "#A8A29E",
    secondary: "#A8A29E",
    buttonText: "#111111",
    cardColor: "#181818",
    surface: "#181818",
    cardOpacity: 0.94,
    border: "#2A2A2A",
    overlay: "rgba(8, 8, 8, 0.56)",
    headingFont: "manrope",
    bodyFont: "inter",
    fontPairingPreset: "manrope-refined",
    radiusStyle: "medium",
  },
  "cathedral-ash": {
    label: "Orman Bakırı",
    description: "Bakır ve zeytin alt tonlu koyu stil.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#131512",
    background: "#131512",
    gradientStart: "#131512",
    gradientEnd: "#131512",
    textColor: "#F3F1EA",
    text: "#F3F1EA",
    mutedText: "#AEB0A3",
    primaryColor: "#B68A56",
    primary: "#B68A56",
    secondaryColor: "#6F7B5C",
    secondary: "#6F7B5C",
    buttonText: "#171511",
    cardColor: "#1B1E1A",
    surface: "#1B1E1A",
    cardOpacity: 0.95,
    border: "#2B3028",
    overlay: "rgba(10, 12, 9, 0.52)",
    headingFont: "outfit",
    bodyFont: "manrope",
    fontPairingPreset: "outfit-modern",
    radiusStyle: "medium",
  },
  "astral-forge": {
    label: "Mürekkep Mavi",
    description: "Lacivert tabanlı serin ve temiz görünüm.",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#10141B",
    background: "#10141B",
    gradientStart: "#10141B",
    gradientEnd: "#10141B",
    textColor: "#EFF4FA",
    text: "#EFF4FA",
    mutedText: "#A9B7C9",
    primaryColor: "#7BA7D9",
    primary: "#7BA7D9",
    secondaryColor: "#4E6FAE",
    secondary: "#4E6FAE",
    buttonText: "#0F1720",
    cardColor: "#171D26",
    surface: "#171D26",
    cardOpacity: 0.94,
    border: "#263243",
    overlay: "rgba(9, 12, 17, 0.54)",
    headingFont: "outfit",
    bodyFont: "inter",
    fontPairingPreset: "outfit-modern",
    radiusStyle: "medium",
  },
} as const;

export type ThemePresetKey = (typeof themePresetOptions)[number];
export type BackgroundType = (typeof backgroundTypeOptions)[number];
export type RadiusStyle = (typeof radiusStyleOptions)[number];
export type ThemeMode = (typeof themeModeOptions)[number];
export type FontPairingPreset = (typeof fontPairingPresetOptions)[number];
export type HeadingFontKey = (typeof headingFontOptions)[number]["value"];
export type BodyFontKey = (typeof bodyFontOptions)[number]["value"];
