export const themePresetOptions = [
  "obsidian-bronze",
  "soft-graphite",
  "midnight-neon",
  "ivory-ink",
  "muted-sand",
  "deep-forest",
  "royal-indigo",
  "clean-slate",
  "sunset-copper",
  "cyber-mint",
] as const;

export const backgroundTypeOptions = ["solid", "gradient", "image"] as const;
export const backgroundOverlayStrengthOptions = ["light", "balanced", "strong", "extra-strong"] as const;
export const backgroundImageSoftnessOptions = ["sharp", "soft", "softer"] as const;
export const backgroundImageFocusOptions = ["center", "top", "left", "right"] as const;
export const radiusStyleOptions = ["small", "medium", "large"] as const;
export const cardFeelOptions = ["subtle", "balanced", "defined"] as const;
export const buttonStyleOptions = ["filled", "soft", "outline"] as const;
export const badgeStyleOptions = ["subtle", "colored"] as const;
export const themeModeOptions = ["dark", "light"] as const;
export const fontPairingPresetOptions = [
  "obsidian-editorial",
  "soft-graphite-neutral",
  "midnight-neon-tech",
  "ivory-editorial",
  "muted-sand-warm",
  "deep-forest-classic",
  "royal-indigo-modern",
  "clean-slate-neutral",
  "sunset-copper-vivid",
  "cyber-mint-tech",
] as const;

export const headingFontOptions = [
  { value: "inter", label: "Inter" },
  { value: "manrope", label: "Manrope" },
  { value: "playfair-display", label: "Playfair Display" },
  { value: "space-grotesk", label: "Space Grotesk" },
  { value: "source-sans-3", label: "Source Sans 3" },
  { value: "cormorant-garamond", label: "Cormorant Garamond" },
  { value: "libre-baskerville", label: "Libre Baskerville" },
  { value: "plus-jakarta-sans", label: "Plus Jakarta Sans" },
  { value: "poppins", label: "Poppins" },
] as const;

export const bodyFontOptions = [
  { value: "inter", label: "Inter" },
  { value: "manrope", label: "Manrope" },
  { value: "dm-sans", label: "DM Sans" },
  { value: "source-sans-3", label: "Source Sans 3" },
  { value: "courier-prime", label: "Courier Prime" },
] as const;

export const themePresets = {
  "obsidian-bronze": {
    label: "Obsidian Bronze",
    description: "Dark premium bronze",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#0E0E0F",
    background: "#0E0E0F",
    gradientStart: "#0E0E0F",
    gradientEnd: "#171719",
    textColor: "#F5F5F5",
    text: "#F5F5F5",
    mutedText: "#A1A1AA",
    primaryColor: "#C6A27A",
    primary: "#C6A27A",
    secondaryColor: "#8E6F4E",
    secondary: "#8E6F4E",
    buttonText: "#181411",
    cardColor: "#171719",
    surface: "#171719",
    cardOpacity: 0.94,
    border: "#2A2A2E",
    overlay: "rgba(10, 10, 12, 0.52)",
    headingFont: "playfair-display",
    bodyFont: "inter",
    fontPairingPreset: "obsidian-editorial",
    radiusStyle: "medium",
  },
  "soft-graphite": {
    label: "Soft Graphite",
    description: "Dark softer contrast",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#18181B",
    background: "#18181B",
    gradientStart: "#18181B",
    gradientEnd: "#232326",
    textColor: "#E5E7EB",
    text: "#E5E7EB",
    mutedText: "#9CA3AF",
    primaryColor: "#9CA3AF",
    primary: "#9CA3AF",
    secondaryColor: "#6B7280",
    secondary: "#6B7280",
    buttonText: "#171717",
    cardColor: "#232326",
    surface: "#232326",
    cardOpacity: 0.94,
    border: "#2F2F33",
    overlay: "rgba(10, 10, 12, 0.5)",
    headingFont: "manrope",
    bodyFont: "inter",
    fontPairingPreset: "soft-graphite-neutral",
    radiusStyle: "medium",
  },
  "midnight-neon": {
    label: "Midnight Neon",
    description: "Dark high-contrast accent",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#050507",
    background: "#050507",
    gradientStart: "#050507",
    gradientEnd: "#111113",
    textColor: "#F9FAFB",
    text: "#F9FAFB",
    mutedText: "#9CA3AF",
    primaryColor: "#22D3EE",
    primary: "#22D3EE",
    secondaryColor: "#0EA5E9",
    secondary: "#0EA5E9",
    buttonText: "#0F1720",
    cardColor: "#111113",
    surface: "#111113",
    cardOpacity: 0.94,
    border: "#1F2937",
    overlay: "rgba(9, 11, 16, 0.54)",
    headingFont: "space-grotesk",
    bodyFont: "dm-sans",
    fontPairingPreset: "midnight-neon-tech",
    radiusStyle: "medium",
  },
  "ivory-ink": {
    label: "Warm Paper",
    description: "Light editorial",
    themeMode: "light",
    backgroundType: "solid",
    backgroundColor: "#F4F1EA",
    background: "#F4F1EA",
    gradientStart: "#F4F1EA",
    gradientEnd: "#FFFFFF",
    textColor: "#1C1917",
    text: "#1C1917",
    mutedText: "#7A7168",
    primaryColor: "#2F2A24",
    primary: "#2F2A24",
    secondaryColor: "#6B5E52",
    secondary: "#6B5E52",
    buttonText: "#F4F1EA",
    cardColor: "#FFFFFF",
    surface: "#FFFFFF",
    cardOpacity: 0.96,
    border: "#E7E0D6",
    overlay: "rgba(10, 10, 12, 0.2)",
    headingFont: "playfair-display",
    bodyFont: "source-sans-3",
    fontPairingPreset: "ivory-editorial",
    radiusStyle: "medium",
  },
  "muted-sand": {
    label: "Muted Sand",
    description: "Light warm minimal",
    themeMode: "light",
    backgroundType: "solid",
    backgroundColor: "#F5EFE6",
    background: "#F5EFE6",
    gradientStart: "#F5EFE6",
    gradientEnd: "#FFFFFF",
    textColor: "#2B2B2B",
    text: "#2B2B2B",
    mutedText: "#6B7280",
    primaryColor: "#A68A64",
    primary: "#A68A64",
    secondaryColor: "#7C6A4D",
    secondary: "#7C6A4D",
    buttonText: "#171511",
    cardColor: "#FFFFFF",
    surface: "#FFFFFF",
    cardOpacity: 0.96,
    border: "#E6E0D4",
    overlay: "rgba(10, 10, 12, 0.2)",
    headingFont: "cormorant-garamond",
    bodyFont: "inter",
    fontPairingPreset: "muted-sand-warm",
    radiusStyle: "medium",
  },
  "deep-forest": {
    label: "Moss Stone",
    description: "Dark natural tone",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#0F1512",
    background: "#0F1512",
    gradientStart: "#0F1512",
    gradientEnd: "#1A231E",
    textColor: "#E6F0EA",
    text: "#E6F0EA",
    mutedText: "#9FB3A7",
    primaryColor: "#5F7A67",
    primary: "#5F7A67",
    secondaryColor: "#3F5A4A",
    secondary: "#3F5A4A",
    buttonText: "#0F1512",
    cardColor: "#1A231E",
    surface: "#1A231E",
    cardOpacity: 0.94,
    border: "#2A3A32",
    overlay: "rgba(9, 12, 10, 0.54)",
    headingFont: "libre-baskerville",
    bodyFont: "source-sans-3",
    fontPairingPreset: "deep-forest-classic",
    radiusStyle: "medium",
  },
  "royal-indigo": {
    label: "Ink Indigo",
    description: "Dark saturated",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#0F1020",
    background: "#0F1020",
    gradientStart: "#0F1020",
    gradientEnd: "#1A1C2E",
    textColor: "#E6E8FF",
    text: "#E6E8FF",
    mutedText: "#A5A9D6",
    primaryColor: "#4C5BD4",
    primary: "#4C5BD4",
    secondaryColor: "#3B44A6",
    secondary: "#3B44A6",
    buttonText: "#F5F3FF",
    cardColor: "#1A1C2E",
    surface: "#1A1C2E",
    cardOpacity: 0.94,
    border: "#2A2D4A",
    overlay: "rgba(8, 9, 20, 0.56)",
    headingFont: "plus-jakarta-sans",
    bodyFont: "inter",
    fontPairingPreset: "royal-indigo-modern",
    radiusStyle: "medium",
  },
  "clean-slate": {
    label: "Clean Slate",
    description: "Light neutral modern",
    themeMode: "light",
    backgroundType: "solid",
    backgroundColor: "#F1F5F9",
    background: "#F1F5F9",
    gradientStart: "#F1F5F9",
    gradientEnd: "#FFFFFF",
    textColor: "#020617",
    text: "#020617",
    mutedText: "#475569",
    primaryColor: "#0F172A",
    primary: "#0F172A",
    secondaryColor: "#334155",
    secondary: "#334155",
    buttonText: "#F8FAFC",
    cardColor: "#FFFFFF",
    surface: "#FFFFFF",
    cardOpacity: 0.96,
    border: "#E2E8F0",
    overlay: "rgba(10, 10, 12, 0.18)",
    headingFont: "inter",
    bodyFont: "inter",
    fontPairingPreset: "clean-slate-neutral",
    radiusStyle: "medium",
  },
  "sunset-copper": {
    label: "Burnt Copper",
    description: "Warm vivid",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#1A120E",
    background: "#1A120E",
    gradientStart: "#1A120E",
    gradientEnd: "#241914",
    textColor: "#F6EDE8",
    text: "#F6EDE8",
    mutedText: "#C9A89A",
    primaryColor: "#A65A3A",
    primary: "#A65A3A",
    secondaryColor: "#7C3F2A",
    secondary: "#7C3F2A",
    buttonText: "#F6EDE8",
    cardColor: "#241914",
    surface: "#241914",
    cardOpacity: 0.94,
    border: "#3A2620",
    overlay: "rgba(12, 8, 7, 0.56)",
    headingFont: "poppins",
    bodyFont: "dm-sans",
    fontPairingPreset: "sunset-copper-vivid",
    radiusStyle: "medium",
  },
  "cyber-mint": {
    label: "Cyber Mint",
    description: "Bright modern tech",
    themeMode: "dark",
    backgroundType: "solid",
    backgroundColor: "#0C1110",
    background: "#0C1110",
    gradientStart: "#0C1110",
    gradientEnd: "#141A19",
    textColor: "#ECFEFF",
    text: "#ECFEFF",
    mutedText: "#99F6E4",
    primaryColor: "#2DD4BF",
    primary: "#2DD4BF",
    secondaryColor: "#14B8A6",
    secondary: "#14B8A6",
    buttonText: "#0C1110",
    cardColor: "#141A19",
    surface: "#141A19",
    cardOpacity: 0.94,
    border: "#1F2A29",
    overlay: "rgba(8, 12, 12, 0.54)",
    headingFont: "space-grotesk",
    bodyFont: "inter",
    fontPairingPreset: "cyber-mint-tech",
    radiusStyle: "medium",
  },
} as const;

export type ThemePresetKey = (typeof themePresetOptions)[number];
export type BackgroundType = (typeof backgroundTypeOptions)[number];
export type BackgroundOverlayStrength = (typeof backgroundOverlayStrengthOptions)[number];
export type BackgroundImageSoftness = (typeof backgroundImageSoftnessOptions)[number];
export type BackgroundImageFocus = (typeof backgroundImageFocusOptions)[number];
export type RadiusStyle = (typeof radiusStyleOptions)[number];
export type CardFeel = (typeof cardFeelOptions)[number];
export type ButtonStyle = (typeof buttonStyleOptions)[number];
export type BadgeStyle = (typeof badgeStyleOptions)[number];
export type ThemeMode = (typeof themeModeOptions)[number];
export type FontPairingPreset = (typeof fontPairingPresetOptions)[number];
export type HeadingFontKey = (typeof headingFontOptions)[number]["value"];
export type BodyFontKey = (typeof bodyFontOptions)[number]["value"];
